(function(){
'use strict';
var E={},S={idx:null,refs:[],tokenMap:{},items:[],headers:[],tab:'important',shown:200,selected:{},sources:[]};
var tabs=[['important','المهم فقط'],['include','مطابق'],['review','مراجعة'],['exclude','المستبعد'],['all','كل النتائج']];
var CATS={
  mobility:['الحركة والنقل','wheelchair','walker','rollator','crutch','cane','gait trainer','gait belt','transfer board','patient lift','standing frame','parallel bars','commode chair','shower chair','مشاية','كرسي متحرك','عكاز','نقل'],
  exercise:['تمارين وتقوية','exercise','resistance band','theraband','dumbbell','weight','pulley','balance board','treadmill','bike','cycle ergometer','therapy ball','finger ladder','shoulder wheel','تمارين','تقوية','مطاط'],
  modality:['أجهزة علاجية','tens','nmes','ifc','fes','electrotherapy','ultrasound therapy','shockwave','laser therapy','traction','cpm','paraffin','hydrocollator','stimulator','diathermy','ليزر','سحب','موجات'],
  assessment:['تقييم وقياس','goniometer','dynamometer','inclinometer','gait analyzer','pressure plate','podoscope','force plate','balance system','measuring tape','jamar','baseline','تقييم','قياس'],
  orthotics:['جبائر ودعامات','splint','brace','orthosis','orthotic','support','collar','immobilizer','abduction brace','afo','kafo','دعامة','جبيرة'],
  prosthetics:['أطراف صناعية','prosthetic','prosthesis','liner','socket','suspension sleeve','transfemoral','transtibial','knee joint','prosthetic foot','طرف صناعي'],
  adl:['أدوات الحياة اليومية','adl','daily living','reacher','grab bar','raised toilet seat','bath chair','button hook','sock aid','shoe horn','adaptive utensil','حياة يومية'],
  furniture:['أثاث علاجي','treatment table','therapy table','plinth','mat table','rehab table','stool','tilt table','home care bed','mattress','طاولة علاج','سرير'],
  consumable:['مستهلكات تأهيل','electrode','ultrasound gel','strap','tape','kinesiology','thermoplastic sheet','elastic loop','hook loop','lead cable','gel','pads','band','جل','تيب','الكترود'],
  rehab:['تأهيل عام','rehabilitation','physiotherapy','physical therapy','occupational therapy','rehab','therapy supplies','therapy equipment','تأهيل','علاج طبيعي']
};
var NEG=[
  ['مختبر','laboratory','reagent','hplc','chromatography','culture','pipette','specimen','microbiology','hematology'],
  ['أسنان','dental','orthodontic','molar','bracket','bonding','dentures','endodontic'],
  ['جراحة','surgical','suture','scalpel','cannula','drill bit','endoscopy','laparoscopy','stent','catheter'],
  ['أشعة/نووي','radiology','contrast','iodide','yttrium','samarium','mci','radioactive','ct scan'],
  ['صيدلية','tablet','capsule','injection','drug','pharmaceutical','vaccine'],
  ['تمريض عام','uniform','syringe','needle','iv set','dressing wound','gauze','oxygen cylinder']
];
var ALIASES={
  name:['name','item','item name','item_name','product','trade name','scientific desc','description','اسم','الاسم','الصنف','اسم الصنف','الوصف','بيان الصنف'],
  desc:['description','desc','details','specification','specifications','long description','item description','material description','items description','المواصفات','تفاصيل','شرح','الوصف'],
  code:['code','sku','item code','item_code','nupco code','nupco_code','moh code','material','material code','catalog','ref','reference','رقم الصنف','كود','رمز','رقم المادة'],
  barcode:['barcode','bar code','gtin','gln','ean','upc','باركود'],
  maker:['manufacturer','brand','company','make','vendor','supplier','المورد','الشركة','الماركة','المصنع'],
  category:['category','group','class','type','sub category','subcategory','الفئة','التصنيف','المجموعة','نوع'],
  qty:['qty','quantity','stock','balance','available','الكمية','المخزون','الرصيد'],
  unit:['unit','uom','pack','الوحدة','وحدة']
};
var NOISE={'and':1,'or':1,'for':1,'with':1,'without':1,'the':1,'each':1,'pair':1,'pack':1,'box':1,'set':1,'size':1,'assorted':1,'medical':1,'supply':1,'supplies':1,'equipment':1,'general':1,'standard':1,'patient':1,'adult':1,'small':1,'medium':1,'large':1};
function gid(x){return document.getElementById(x)}
function init(){['file','drop','fname','fsub','bar','status','q','cat','src','imgf','sample','tabs','stats','qa','count','selectedCount','res','more','selectVisible','clearSelected','exportSelected','exportInclude','exportReview','exportExcluded'].forEach(function(k){E[k]=gid(k)});Object.keys(CATS).forEach(function(k){var o=document.createElement('option');o.value=k;o.textContent=CATS[k][0];E.cat.appendChild(o)});paintTabs();bind();loadIndex();render()}
function bind(){E.file.onchange=function(ev){handleFiles(Array.from(ev.target.files||[]))};E.drop.ondragover=function(e){e.preventDefault();E.drop.classList.add('drag')};E.drop.ondragleave=function(){E.drop.classList.remove('drag')};E.drop.ondrop=function(e){e.preventDefault();E.drop.classList.remove('drag');handleFiles(Array.from(e.dataTransfer.files||[]))};[E.q,E.cat,E.src,E.imgf].forEach(function(x){['input','change'].forEach(function(ev){x.addEventListener(ev,function(){S.shown=200;render()})})});E.sample.onclick=sample;E.selectVisible.onclick=function(){list().slice(0,S.shown).forEach(function(x){S.selected[x.id]=1});render()};E.clearSelected.onclick=function(){S.selected={};render()};E.exportSelected.onclick=function(){exportRows('selected')};E.exportInclude.onclick=function(){exportRows('include')};E.exportReview.onclick=function(){exportRows('review')};E.exportExcluded.onclick=function(){exportRows('exclude')}}
function setStatus(t,p){E.status.textContent=t||'';E.bar.style.width=(p||0)+'%'}
function rest(){return new Promise(function(r){setTimeout(r,0)})}
async function loadIndex(){var paths=['product_index.json','download/product_index.json','../download/product_index.json'];for(var i=0;i<paths.length;i++){try{var r=await fetch(paths[i],{cache:'no-cache'});if(r.ok){S.idx=await r.json();buildRefs();setStatus('تم تحميل فهرس التأهيل: '+S.refs.length+' صنف مرجعي.',100);qa();return}}catch(e){}}setStatus('لم يتم تحميل فهرس المنتجات. سيعمل التصنيف النصي فقط.',0);qa()}
function buildRefs(){S.refs=[];S.tokenMap={};if(!S.idx)return;var seen={};function add(key,item){if(!item)return;var id=String(item.num||item.code||key||item.desc||'');if(!id||seen[id])return;seen[id]=1;var d=String(item.desc||'');var ref={id:id,num:item.num||'',code:item.code||'',barcode:item.barcode||'',desc:d,img:item.img||'',cat:classify(d).key};S.refs.push(ref);tokensOf(d).slice(0,18).forEach(function(t){if(!S.tokenMap[t])S.tokenMap[t]=[];if(S.tokenMap[t].length<150)S.tokenMap[t].push(ref)})}Object.keys(S.idx.byCode||{}).forEach(function(k){var it=S.idx.byCode[k];it.code=k;add(k,it)});Object.keys(S.idx.byBarcode||{}).forEach(function(k){var it=S.idx.byBarcode[k];it.barcode=k;add(k,it)});(S.idx.byDesc||[]).forEach(function(it){add(it.num,it)})}
async function handleFiles(files){if(!files.length)return;S.items=[];S.selected={};S.shown=200;S.sources=[];E.fname.textContent=files.length===1?files[0].name:files.length+' ملفات';E.fsub.textContent='قراءة الملفات...';render();var all=[],total=0;try{for(var f=0;f<files.length;f++){setStatus('قراءة '+files[f].name,5);var rows=await readFile(files[f]);total+=rows.length;for(var i=0;i<rows.length;i++){rows[i]._sourceFile=files[f].name;all.push(rows[i])}await rest()}setStatus('تحليل '+all.length+' صف...',15);var out=[];for(var j=0;j<all.length;j++){var item=analyze(toRow(all[j],j),j);if(item)out.push(item);if(j%120===0){S.items=out;setStatus('تحليل '+(j+1)+' / '+all.length,15+Math.round(j/all.length*80));refreshSources();stats();await rest()}}S.items=out;refreshSources();setStatus('تم التحليل.',100);E.fsub.textContent=fmt(files.reduce(function(a,b){return a+b.size},0))+' - '+out.length+' نتيجة من '+total+' صف';render()}catch(e){console.error(e);setStatus('فشل: '+(e.message||e),0);alert('فشل التحليل: '+(e.message||e))}}
async function readFile(file){var n=file.name.toLowerCase();if(n.endsWith('.json')){var j=JSON.parse(await file.text());var arr=Array.isArray(j)?j:(j.products||j.rows||j.data||[]);return arr.map(function(x,i){x._row=i+1;return x})}if(n.endsWith('.xlsx')||n.endsWith('.xls')){if(!window.XLSX)throw Error('تعذر تحميل Excel');var ab=await file.arrayBuffer();var wb=XLSX.read(ab,{type:'array'});var out=[];for(var s=0;s<wb.SheetNames.length;s++){var name=wb.SheetNames[s];var arr=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',blankrows:false});out=out.concat(rowsFromArray(arr,name));await rest()}return out}var txt=await file.text();return rowsFromArray(parseCSV(txt,n.endsWith('.tsv')?'\t':','),'Sheet1')}
function parseCSV(txt,sep){var rows=[],row=[],val='',q=false;for(var i=0;i<txt.length;i++){var c=txt[i],n=txt[i+1];if(c==='"'){if(q&&n==='"'){val+='"';i++}else q=!q}else if(c===sep&&!q){row.push(val);val=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(val);if(row.some(function(x){return String(x).trim()}))rows.push(row);row=[];val=''}else val+=c}row.push(val);if(row.some(function(x){return String(x).trim()}))rows.push(row);return rows}
function rowsFromArray(arr,sheet){var hi=detectHeader(arr),headers=[];if(hi>=0)headers=arr[hi].map(function(h){return String(h||'').trim()});var out=[];for(var i=hi>=0?hi+1:0;i<arr.length;i++){var cells=arr[i]||[];if(!cells.some(function(x){return String(x||'').trim()}))continue;var obj={_sheet:sheet,_row:i+1,_cells:cells};headers.forEach(function(h,j){if(h)obj[h]=cells[j]});out.push(obj)}return out}
function detectHeader(arr){var best=-1,bs=0;for(var i=0;i<Math.min(12,arr.length);i++){var row=arr[i]||[],sc=0;row.forEach(function(c){var h=normHeader(c);Object.keys(ALIASES).forEach(function(k){if(ALIASES[k].map(normHeader).indexOf(h)>-1)sc+=3});if(/[a-z؀-ۿ]/i.test(String(c)))sc++});if(sc>bs){bs=sc;best=i}}return bs>=3?best:-1}
function toRow(r,i){if(Array.isArray(r))return{row:i+1,cells:r,source:'',sheet:''};if(r&&r._cells)return{row:r._row||i+1,cells:r._cells,obj:r,source:r._sourceFile||'',sheet:r._sheet||''};return{row:r._row||i+1,cells:Object.values(r||{}),obj:r,source:r._sourceFile||'',sheet:r._sheet||''}}
function analyze(r,idx){var vals=r.cells.map(function(v){return String(v==null?'':v).trim()}).filter(Boolean);if(!vals.length)return null;var raw=vals.join(' | ');var obj=r.obj||{};var code=pick(obj,'code')||extractCode(raw);var bc=pick(obj,'barcode')||extractBarcode(raw);var maker=pick(obj,'maker');var sourceCat=pick(obj,'category');var name=pick(obj,'name');var desc=pick(obj,'desc')||bestDesc(vals,code,bc)||name||raw;var corpus=[name,desc,maker,sourceCat,raw].join(' ');var ref=matchRef(code,bc,corpus);var cls=classify(corpus);var neg=negativeScore(corpus);var score=0,why=[];if(ref){score+=ref.basis==='barcode'?82:ref.basis==='code'?78:55;why.push(ref.basis==='barcode'?'مطابقة باركود مع الفهرس':ref.basis==='code'?'مطابقة كود مع الفهرس':'تشابه وصف مع فهرس التأهيل')}
if(cls.key!=='other'){score+=cls.score;why.push(CATS[cls.key][0])}if(/REHAB|PHYSIO|PHYSICAL THERAPY|OCCUPATIONAL THERAPY|WHEELCHAIR|ORTHOSIS|PROSTH|SPLINT|BRACE|GAIT|TRANSFER|TENS|NMES|ULTRASOUND|SHOCKWAVE/i.test(corpus)){score+=12;why.push('مصطلح تأهيل واضح')}if(sourceCat&&/REHAB|PHYSIO|WHEELCHAIR|ORTHO|PROSTH/i.test(sourceCat)){score+=18;why.push('تصنيف المصدر يخدم التأهيل')}if(maker&&/CHATTANOOGA|BTL|STORZ|ENRAF|DJO|DONJOY|OSSUR|ÖSSUR|OTTOBOCK|SUNRISE|INVACARE|DRIVE MEDICAL|THERABAND|RIFTON|PERFORMANCE HEALTH|BIODEx|JAMAR/i.test(maker)){score+=10;why.push('شركة/ماركة مرجحة للتأهيل')}if(neg.score){score-=neg.score;why.push('استبعاد محتمل: '+neg.label)}score=Math.max(0,Math.min(100,score));var status=score>=48&&(!neg.score||ref)?'include':score>=25?'review':'exclude';var cat=ref&&ref.item&&ref.item.cat&&ref.item.cat!=='other'?ref.item.cat:cls.key;var id='r'+idx+'_'+(code||bc||hash(raw));return{id:id,row:r.row,sheet:r.sheet||'',source:r.source||'',raw:raw,code:code,bc:bc,maker:maker,sourceCat:sourceCat,name:name||desc,desc:desc,cat:cat,catName:CATS[cat]?CATS[cat][0]:'غير مصنف',score:score,status:status,why:why,match:ref?ref.basis:'no_match',refNum:ref&&ref.item?ref.item.num:'',refDesc:ref&&ref.item?ref.item.desc:'',img:ref&&ref.item&&ref.item.img?imgPath(ref.item.img):''}}
function pick(obj,type){if(!obj)return'';var aliases=ALIASES[type]||[];var map={};Object.keys(obj).forEach(function(k){map[normHeader(k)]=obj[k]});for(var i=0;i<aliases.length;i++){var v=map[normHeader(aliases[i])];if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim()}return''}
function extractCode(s){var m=String(s).match(/\bM[A-Z]{2}\d{5}(?:-\d{3})?\b/i)||String(s).match(/\bP-\d{4,}\b/i);return m?m[0].toUpperCase():''}
function extractBarcode(s){var m=String(s).match(/\b\d{12,14}\b/)||String(s).match(/\b\d{8,11}\b/);return m?m[0]:''}
function bestDesc(vals,code,bc){var a=vals.filter(function(v){return v!==code&&v!==bc&&!/^\d+$/.test(v)&&String(v).length>2});a.sort(function(x,y){return y.length-x.length});return a[0]||''}
function classify(text){var low=norm(text),best={key:'other',score:0};Object.keys(CATS).forEach(function(k){var sc=0;CATS[k].slice(1).forEach(function(t){var nt=norm(t);if(nt&&low.indexOf(nt)>-1)sc+=nt.indexOf(' ')>-1?16:9});if(sc>best.score)best={key:k,score:Math.min(42,sc)}});return best}
function negativeScore(text){var low=norm(text),best={score:0,label:''};NEG.forEach(function(group){var label=group[0],sc=0;group.slice(1).forEach(function(t){if(low.indexOf(norm(t))>-1)sc+=18});if(sc>best.score)best={score:Math.min(55,sc),label:label}});return best}
function matchRef(code,bc,corpus){if(!S.idx)return null;var c=String(code||'').toUpperCase();if(c&&S.idx.byCode&&S.idx.byCode[c])return{basis:'code',item:prepRef(S.idx.byCode[c])};if(bc&&S.idx.byBarcode&&S.idx.byBarcode[bc])return{basis:'barcode',item:prepRef(S.idx.byBarcode[bc])};var toks=tokensOf(corpus),cand={},best=null,bs=0;toks.forEach(function(t){(S.tokenMap[t]||[]).forEach(function(r){cand[r.id]=(cand[r.id]||0)+1})});Object.keys(cand).forEach(function(id){var r=S.refs.find(function(x){return x.id===id});if(!r)return;var sc=cand[id]*12;var d=norm(r.desc);toks.forEach(function(t){if(d.indexOf(t)>-1)sc+=2});if(sc>bs){bs=sc;best=r}});return best&&bs>=38?{basis:'description',item:best}:null}
function prepRef(it){return {num:it.num||'',desc:it.desc||'',img:it.img||'',cat:classify(it.desc||'').key}}
function imgPath(img){if(!img)return'';if(/^https?:/i.test(img)||img.indexOf('/')>-1)return img;return 'product_images/'+img}
function paintTabs(){E.tabs.innerHTML=tabs.map(function(t){return'<button class="tab '+(S.tab===t[0]?'on':'')+'" data-t="'+t[0]+'">'+t[1]+'</button>'}).join('');Array.from(E.tabs.querySelectorAll('button')).forEach(function(b){b.onclick=function(){S.tab=b.dataset.t;S.shown=200;paintTabs();render()}})}
function refreshSources(){var seen={};S.sources=[];S.items.forEach(function(x){if(x.source&&!seen[x.source]){seen[x.source]=1;S.sources.push(x.source)}});var old=E.src.value;E.src.innerHTML='<option value="all">كل الملفات</option>'+S.sources.map(function(s){return'<option>'+esc(s)+'</option>'}).join('');E.src.value=S.sources.indexOf(old)>-1?old:'all'}
function list(){var q=norm(E.q.value),cat=E.cat.value,src=E.src.value,imgf=E.imgf.value;return S.items.filter(function(x){return S.tab==='all'||(S.tab==='important'?x.status!=='exclude':x.status===S.tab)}).filter(function(x){return cat==='all'||x.cat===cat}).filter(function(x){return src==='all'||x.source===src}).filter(function(x){return imgf==='all'||(imgf==='with'?!!x.img:!x.img)}).filter(function(x){return!q||norm([x.raw,x.desc,x.code,x.bc,x.maker,x.catName,x.source].join(' ')).indexOf(q)>-1}).sort(function(a,b){return b.score-a.score||a.row-b.row})}
function render(){stats();qa();if(!S.items.length){E.count.textContent='لا توجد نتائج.';E.selectedCount.textContent='المحدد: 0';E.res.className='empty';E.res.innerHTML='ارفع ملف أو اضغط تجربة.';E.more.innerHTML='';return}var v=list();E.count.textContent='ظاهر '+Math.min(v.length,S.shown)+' من '+v.length+' - إجمالي '+S.items.length;E.selectedCount.textContent='المحدد: '+Object.keys(S.selected).length;E.res.className=v.length?'grid':'empty';E.res.innerHTML=v.length?v.slice(0,S.shown).map(card).join(''):'لا توجد نتائج مطابقة.';E.more.innerHTML=v.length>S.shown?'<button class="btn" id="moreBtn">عرض المزيد</button>':'';var mb=gid('moreBtn');if(mb)mb.onclick=function(){S.shown+=200;render()};Array.from(document.querySelectorAll('.chk')).forEach(function(c){c.onchange=function(){if(c.checked)S.selected[c.dataset.id]=1;else delete S.selected[c.dataset.id];render()}})}
function stats(){var a=S.items,inc=a.filter(function(x){return x.status==='include'}).length,rev=a.filter(function(x){return x.status==='review'}).length,exc=a.filter(function(x){return x.status==='exclude'}).length,img=a.filter(function(x){return x.img}).length,match=a.filter(function(x){return x.match!=='no_match'}).length;E.stats.innerHTML=[['محلل',a.length,''],['مطابق',inc,'ok'],['مراجعة',rev,'warn'],['مستبعد',exc,'bad'],['مطابق فهرس',match,'ok'],['صور',img,''],['مصادر',S.sources.length,'']].map(function(s){return'<div class="stat '+s[2]+'"><b>'+s[1]+'</b><span>'+s[0]+'</span></div>'}).join('')}
function qa(){var lines=[];lines.push(['ok','الفهرس المرجعي: '+(S.idx?S.refs.length+' صنف':'غير محمل')]);if(S.items.length){lines.push(['ok','التحليل يعمل على دفعات ولا يرندر كل النتائج دفعة واحدة.']);var ex=S.items.filter(function(x){return x.status==='exclude'}).length;if(ex)lines.push(['warn','تم استبعاد '+ex+' صف؛ راجعها من تبويب المستبعد قبل التصدير النهائي.'])}E.qa.innerHTML=lines.map(function(x){return'<div class="qaLine '+x[0]+'">'+esc(x[1])+'</div>'}).join('')}
function card(x){var cls=x.status==='include'?'ok':x.status==='review'?'warn':'bad';return'<article class="card '+x.status+'"><div class="top"><input class="chk" type="checkbox" data-id="'+esc(x.id)+'" '+(S.selected[x.id]?'checked':'')+'><div>'+(x.img?'<img class="img" src="'+esc(x.img)+'" loading="lazy" alt="">':'')+'<div class="title">'+esc(x.name||x.desc)+'</div><div class="small">صف '+x.row+(x.sheet?' - '+esc(x.sheet):'')+(x.source?' - '+esc(x.source):'')+'</div></div></div><div><span class="tag '+cls+'">'+lab(x.status)+'</span><span class="tag">'+esc(x.catName)+'</span><span class="tag">'+x.score+'%</span><span class="tag">'+(x.match!=='no_match'?'مطابق: '+x.match:'بدون مطابقة مباشرة')+'</span><span class="tag">'+(x.img?'صورة من الفهرس':'بدون صورة')+'</span></div><div class="kv"><span class="tag mono">'+esc(x.code||'NO CODE')+'</span><span class="tag mono">'+esc(x.bc||'NO BARCODE')+'</span></div><div class="desc">'+esc(x.desc)+'</div>'+(x.refDesc&&x.refDesc!==x.desc?'<details><summary>وصف الفهرس</summary><div class="desc">'+esc(x.refDesc)+'</div></details>':'')+'<div class="reason">'+esc(x.why.join('، ')||'لا يوجد سبب واضح')+'</div></article>'}
function sample(){var rows=[{name:'PACER GAIT TRAINER WITH ALL ACCESSORIES SIZE MEDIUM',manufacturer:'RIFTON',description:'floor to top arm prompt stability base maximum working load 150 lbs',sku:'GT-MED-01',_sourceFile:'sample'}, {name:'STENT GRAFT ENDOVASCULAR FOR ABDOMINAL AORTIC ANEURYSM',manufacturer:'COOK MEDICAL',description:'sterile vascular graft',sku:'ST-900',_sourceFile:'sample'}, {name:'SYSTEM EASY TRANSFER 32 INCH S-SHAPED TRANSFER BOARD',manufacturer:'PERFORMANCE HEALTHCARE',description:'transfer bed to wheelchair',sku:'TB-32',_sourceFile:'sample'}, {name:'THERABAND RESISTANCE BAND GREEN',manufacturer:'THERABAND',description:'elastic band for strengthening exercise',sku:'RB-GREEN',_sourceFile:'sample'}, {name:'HIP ABDUCTION BRACE ADJUSTABLE LARGE',barcode:'4224170200100',description:'orthopedic hip brace',_sourceFile:'sample'}, {name:'STERILE SYRINGE 10ML WITH NEEDLE',description:'general disposable',_sourceFile:'sample'}];S.items=rows.map(function(r,i){return analyze(toRow(r,i),i)}).filter(Boolean);refreshSources();S.shown=200;setStatus('تم تحميل عينة دعم القرار.',100);render()}
function exportRows(mode){var rows=mode==='selected'?S.items.filter(function(x){return S.selected[x.id]}):S.items.filter(function(x){return x.status===mode});if(!rows.length){alert('لا توجد صفوف للتصدير');return}var out=rows.map(function(x){return{decision:x.status,score:x.score,category:x.catName,match:x.match,code:x.code,barcode:x.bc,name:x.name,description:x.desc,manufacturer:x.maker,source_file:x.source,sheet:x.sheet,row:x.row,has_image:!!x.img,reference_num:x.refNum,reason:x.why.join(' | ')}});download('rehab_decision_'+mode+'.csv',toCSV(out))}
function toCSV(rows){var h=Object.keys(rows[0]||{}),escv=function(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"'};return '\ufeff'+[h.join(','),].concat(rows.map(function(r){return h.map(function(k){return escv(r[k])}).join(',')})).join('\n')}
function download(name,content){var a=document.createElement('a'),b=new Blob([content],{type:'text/csv;charset=utf-8'});a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},0)}
function tokensOf(s){return norm(s).split(' ').filter(function(t){return t.length>2&&!NOISE[t]&&!/^\d+$/.test(t)}).slice(0,80)}
function norm(s){return String(s||'').toLowerCase().replace(/[\u064b-\u065f\u0670]/g,'').replace(/[إأآا]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ـ/g,'').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim()}
function normHeader(h){return norm(h).replace(/\s+/g,' ')}
function hash(s){var h=0;for(var i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h).toString(36)}
function lab(s){return s==='include'?'مطابق':s==='review'?'مراجعة':'مستبعد'}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(m){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
function fmt(b){return b<1024?b+' B':b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(1)+' MB'}
init();
})();