(function(){
var E={},S={idx:null,items:[],tab:'important',shown:200};
var tabs=[['important','المهم فقط'],['accept','مطابق'],['review','مراجعة'],['all','كل النتائج'],['reject','المستبعد']];
var cats={mobility:['الحركة والنقل','walker','wheelchair','crutch','cane','gait','transfer','rollator','walking frame','parallel bar','مشاية','كرسي متحرك','عكاز'],exercise:['تمارين وتقوية','exercise','resistance','theraband','dumbbell','weight','finger ladder','shoulder wheel','pulley','balance board','treadmill','bike','تمارين','تقوية','مطاط'],modality:['أجهزة علاجية','tens','nmes','ifc','fes','electrotherapy','ultrasound','shockwave','laser','paraffin','traction','cpm','stimulator','ليزر','سحب'],assessment:['تقييم وقياس','goniometer','dynamometer','gait analyzer','podoscope','measuring tape','inclinometer','تقييم','قياس'],furniture:['أثاث علاجي','treatment table','plinth','therapy mat','stool','home care bed','mattress','سرير','طاولة علاج'],orthotics:['جبائر وتقويم','splint','orthosis','orthotic','prosthetic','brace','collar','cast','جبيرة','دعامة'],adl:['أدوات الحياة اليومية','adl','daily living','reacher','grab bar','toilet seat','bath chair','حياة يومية'],consumable:['مستهلكات علاج طبيعي','electrode','gel','strap','tape','kinesio','bandage','lead cable','جل','الكترود','تيب'],rehab:['تأهيل عام','rehabilitation','physiotherapy','physical therapy','occupational therapy','rehab','therapy','تأهيل','علاج طبيعي']};
function gid(x){return document.getElementById(x)}
function init(){['file','fname','fsub','bar','status','q','cat','imgf','sample','tabs','stats','count','res','more'].forEach(function(k){E[k]=gid(k)});Object.keys(cats).forEach(function(k){var o=document.createElement('option');o.value=k;o.textContent=cats[k][0];E.cat.appendChild(o)});paintTabs();bind();loadIndex();render()}
function bind(){E.file.onchange=function(ev){if(ev.target.files[0])handle(ev.target.files[0])};[E.q,E.cat,E.imgf].forEach(function(x){x.oninput=function(){S.shown=200;render()}});E.sample.onclick=sample}
function setStatus(t,p){E.status.textContent=t;E.bar.style.width=(p||0)+'%'}
function rest(){return new Promise(function(r){setTimeout(r,0)})}
async function loadIndex(){var paths=['product_index.json','download/product_index.json','../download/product_index.json'];for(var i=0;i<paths.length;i++){try{var r=await fetch(paths[i],{cache:'force-cache'});if(r.ok){S.idx=await r.json();setStatus('تم تحميل فهرس الصور.',100);return}}catch(e){}}setStatus('لم يتم تحميل فهرس الصور. التحليل النصي يعمل.',0)}
async function handle(file){try{S.items=[];S.shown=200;E.fname.textContent=file.name;E.fsub.textContent=fmt(file.size)+' - قراءة';render();setStatus('قراءة الملف...',10);var rows=await readFile(file);setStatus('تحليل '+rows.length+' صف...',20);var out=[];for(var i=0;i<rows.length;i++){var item=analyze(toRow(rows[i],i));if(item)out.push(item);if(i%100===0){S.items=out;setStatus('تحليل '+(i+1)+' / '+rows.length,20+Math.round(i/rows.length*70));stats();await rest()}}S.items=out;setStatus('تم التحليل.',100);E.fsub.textContent=fmt(file.size)+' - '+out.length+' صف';render()}catch(e){console.error(e);setStatus('فشل: '+(e.message||e),0);alert('فشل التحليل: '+(e.message||e))}}
async function readFile(file){var n=file.name.toLowerCase();if(n.endsWith('.json')){var j=JSON.parse(await file.text());return Array.isArray(j)?j:(j.rows||[])}if(n.endsWith('.xlsx')||n.endsWith('.xls')){if(!window.XLSX)throw Error('تعذر تحميل Excel');var ab=await file.arrayBuffer();var wb=XLSX.read(ab,{type:'array'});var out=[];for(var s=0;s<wb.SheetNames.length;s++){var name=wb.SheetNames[s];var arr=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',blankrows:false});for(var i=0;i<arr.length;i++)out.push({sheet:name,row:i+1,cells:arr[i]});await rest()}return out}var sep=n.endsWith('.tsv')?'\t':',';return (await file.text()).split(/\r?\n/).filter(Boolean).map(function(line,i){return{row:i+1,cells:line.split(sep)}})}
function toRow(r,i){if(Array.isArray(r))return{row:i+1,cells:r};if(r&&r.cells)return r;return{row:i+1,cells:Object.values(r||{})}}
function analyze(r){var vals=r.cells.map(function(v){return String(v==null?'':v).trim()}).filter(Boolean);if(!vals.length)return null;var raw=vals.join(' | ');var code=(raw.match(/\bM[A-Z]{2}\d{5}(?:-\d{3})?\b/i)||[''])[0];var bc=(raw.match(/\b\d{8,14}\b/)||[''])[0];var desc=bestDesc(vals,code,bc)||raw;var cat=classify(raw+' '+desc);var m=match(code,bc);var score=0,why=[];if(code){score+=10;why.push('كود')}if(bc){score+=8;why.push('باركود')}if(m&&m.basis==='code'){score+=36;why.push('صورة بالكود')}else if(m){score+=34;why.push('صورة بالباركود')}if(cat.key!=='other'){score+=cat.score;why.push(cats[cat.key][0])}if(/REHAB|PHYSIO|THERAPY|EXERCISE|WALK|GAIT|TENS|ULTRASOUND|TRACTION|SPLINT|ORTHOSIS/i.test(raw)){score+=10;why.push('قرينة تخصصية')}var status=score>=32&&cat.key!=='other'?'accept':score>=20?'review':'reject';return{row:r.row,sheet:r.sheet||'',raw:raw,code:code,bc:bc,desc:desc,cat:cat.key,catName:cats[cat.key]?cats[cat.key][0]:'غير مصنف',score:Math.min(100,score),why:why,status:status,img:m&&m.item&&m.item.img?'product_images/'+m.item.img:''}}
function bestDesc(vals,code,bc){var a=vals.filter(function(v){return v!==code&&v!==bc&&!/^\d+$/.test(v)});a.sort(function(x,y){return y.length-x.length});return a[0]||''}
function classify(text){var low=String(text).toLowerCase(),best={key:'other',score:0};Object.keys(cats).forEach(function(k){var sc=0;cats[k].slice(1).forEach(function(t){if(low.indexOf(String(t).toLowerCase())>-1)sc+=String(t).indexOf(' ')>-1?14:9});if(sc>best.score)best={key:k,score:Math.min(38,sc)}});return best}
function match(code,bc){if(!S.idx)return null;var c=String(code||'').toUpperCase();if(c&&S.idx.byCode&&S.idx.byCode[c])return{basis:'code',item:S.idx.byCode[c]};if(bc&&S.idx.byBarcode&&S.idx.byBarcode[bc])return{basis:'barcode',item:S.idx.byBarcode[bc]};return null}
function paintTabs(){E.tabs.innerHTML=tabs.map(function(t){return'<button class="tab '+(S.tab===t[0]?'on':'')+'" data-t="'+t[0]+'">'+t[1]+'</button>'}).join('');Array.from(E.tabs.querySelectorAll('button')).forEach(function(b){b.onclick=function(){S.tab=b.dataset.t;S.shown=200;paintTabs();render()}})}
function list(){var q=E.q.value.trim().toLowerCase(),cat=E.cat.value,imgf=E.imgf.value;return S.items.filter(function(x){return S.tab==='all'||(S.tab==='important'?x.status!=='reject':x.status===S.tab)}).filter(function(x){return cat==='all'||x.cat===cat}).filter(function(x){return imgf==='all'||(imgf==='with'?!!x.img:!x.img)}).filter(function(x){return!q||(x.raw+' '+x.desc+' '+x.code+' '+x.bc).toLowerCase().indexOf(q)>-1}).sort(function(a,b){return b.score-a.score||a.row-b.row})}
function render(){stats();if(!S.items.length){E.count.textContent='لا توجد نتائج.';E.res.className='empty';E.res.innerHTML='ارفع ملف أو اضغط تجربة.';E.more.innerHTML='';return}var v=list();E.count.textContent='ظاهر '+Math.min(v.length,S.shown)+' من '+v.length+' - إجمالي '+S.items.length;E.res.className=v.length?'grid':'empty';E.res.innerHTML=v.length?v.slice(0,S.shown).map(card).join(''):'لا توجد نتائج مطابقة.';E.more.innerHTML=v.length>S.shown?'<button class="btn" id="moreBtn">عرض المزيد</button>':'';var mb=gid('moreBtn');if(mb)mb.onclick=function(){S.shown+=200;render()}}
function stats(){var a=S.items,acc=a.filter(function(x){return x.status==='accept'}).length,rev=a.filter(function(x){return x.status==='review'}).length,img=a.filter(function(x){return x.img}).length;E.stats.innerHTML=[['محلل',a.length],['مطابق',acc],['مراجعة',rev],['صور',img]].map(function(s){return'<div class="stat"><b>'+s[1]+'</b><span>'+s[0]+'</span></div>'}).join('')}
function card(x){return'<article class="card '+x.status+' '+(x.img?'imgok':'')+'"><div class="top">'+(x.img?'<img class="img" src="'+esc(x.img)+'" loading="lazy" alt="">':'')+'<div><div class="title">'+esc(x.desc)+'</div><div class="muted">صف '+x.row+(x.sheet?' - '+esc(x.sheet):'')+'</div></div></div><div><span class="tag">'+lab(x.status)+'</span><span class="tag">'+esc(x.catName)+'</span><span class="tag">'+x.score+'%</span><span class="tag">'+(x.img?'لها صورة':'بدون صورة')+'</span></div><div><span class="tag mono">'+esc(x.code||'NO CODE')+'</span><span class="tag mono">'+esc(x.bc||'NO BARCODE')+'</span></div><div class="muted">'+esc(x.why.join('، '))+'</div></article>'}
function sample(){S.items=[['MHC40019','422516','WALKER FRONT WHEEL ADULT'],['MRH10053','1234567890123','LASER HIGH INTENSITY THERAPY'],['ABC','999','SYRINGE 10 ML GENERAL MEDICAL'],['','4225160806300','RESISTANCE EXERCISE BAND LATEX FREE']].map(function(r,i){return analyze(toRow(r,i))}).filter(Boolean);S.shown=200;render();setStatus('تم تحميل عينة.',100)}
function lab(s){return s==='accept'?'مطابق':s==='review'?'مراجعة':'مستبعد'}function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(m){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}function fmt(b){return b<1024?b+' B':b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(1)+' MB'}
init();
})();
